id: A7908590D
title: Supplication to Lord Mila Shepa Dorje
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:32:31.000589
  last_modified_at: 2022-03-01 01:32:31.000593
