id: A7908590D
title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven Line Prayer
  (Addendum)'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:32:30.998829
  last_modified_at: 2022-03-01 01:32:30.998857
