id: A7908590D
title: 'The Shower of Blessings: A Prayer'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:32:31.001661
  last_modified_at: 2022-03-01 01:32:31.001664
